### ISSUE TITLE
Webhook Configuration

### ISSUE THREAD

**Issue by Johns-b** [Comcast/caduceus#120]
I am unable to configure webhooks to the caduceus server. I have the latest release of caduceus setup, and am able to trace notification message exchange from the parodus client till caduceus.I am currently using a mock SNS (https://github.com/s12v/sns). When I configure a new webhook using the '/hook' post request, I get a 'Success' response with a 200 OK status. However when I list all the registered hooks using '/hooks' API it responds with an empty array '[]'. There is also no communication from caduceus to the webhook. I have written a webhook server for testing this, but have also tried it with 'ngrok' proxy server and both shows no communication from caduceus.

The Debug log of caduceus shows a 'not a compact JWS' error every time I make an http request to caduceus. It also keeps repeating the following log related to SOA even though I have not configured SOA in 'caduceus.yaml'. There is no other errors in the debug log.

{"caller":"sns.go:247","endpoint":"XX.XX.XX.XX:6000","error":"dial tcp [::1]:5079: connect: connection refused","level":"debug","msg":"checking if server's DNS is ready","response":"\u003cnil\u003e MsgHdr","ts":"2019-02-19T06:08:14.850261431Z"}

**Comment by schmidtw** [comment]
@Johns-b If you get an empty array from caduceus, that means that it's list is empty.  The way SNS works for scytale->caduceus is not ideal as it introduces the need to wait for 5 minutes before caduceus can start sending messages (to ensure it has the full list of notifications to fulfill).  Does the empty array `[]` happen after 5 minutes?

On the SOA, that is present to ensure the DNS name of the local machine is able to work with SNS (otherwise SNS gets into a bad state).  I think that it doesn't skip the check is a bug to file.

**Comment by schmidtw** [comment]
@Johns-b, I wanted to follow up with you to see if you need something else or if I can close this issue.

**Comment by Johns-b** [comment]
@schmidtw, I switched to actual AWS-SNS and  updated the Caduceus version and everything worked fine. Sorry for the delay in my reply. Thank you for your help.
