### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by davidrneves** [Comcast/caduceus#72]
When I try to build caduceus master branch in a centOS 7 machine with go build, the go compiler gives the following error:

./outboundSender.go:495:27: multiple-value uuid.NewV4() in single-value context

This seems to be related with the following issue: https://github.com/hlandau/acme/issues/293
This issue is due to an upstream API change in the github.com/satori/go.uuid package, specifically the change for satori/go.uuid#18. (https://godoc.org/github.com/satori/go.uuid#NewV4)

A simple fix would be:

if "" == tid {
  randUuid, err: = uuid.NewV4()

  if err != nil {
    logging.Error(obs.logger).Log(logging.MessageKey(), "New Post request", "url", obs.listener.Config.URL,
      logging.ErrorKey(), err)
     // Handle error
  } else {
    tid = randUuid.String()
  }
}

**Comment by schmidtw** [comment]
To get the dependencies, are you using `glide install` or `go get`?

I've got caduceus pinned to f58768cc1a7a7e77a3bd49e98cdd21419399b6a3 of satori/go.uuid (latest release 1.2).

I'm not opposed to moving the revision we're building with, but noticed that my build failed due to it being pinned to the older release of the uuid.

**Comment by schmidtw** [comment]
To build, I do the following:

```
cd ~/Projects/caduceus
export GOPATH=`pwd`
cd src
glide install
cd caduceus
go build
```

**Comment by davidrneves** [comment]
I was using "go get" to install the project dependencies. With "glide install" the error is fixed. Thanks for your help.
